name: Noorse site CI

on:
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
#      - uses: ./.github/run-backstop
#      - uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: backstop-test
#          path: backstop_data/
#
