name: Noorse site CI

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [master]

jobs:
  build-prod:
    runs-on: ubuntu-latest
    name: Build PROD
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn build
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GA_TRACKING_ID: ${{secrets.GA_TRACKING_ID}}
          CONTENTFUL_TOKEN: ${{secrets.CONTENTFUL_TOKEN}}
          PROD: true
      - name: Deploy
        uses: nwtgck/actions-netlify@v1
        id: deploy-prod
        with:
          publish-dir: './public'
          production-deploy: ${{ startsWith(github.ref, 'refs/tags/v') }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy ${{ github.ref }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: cfb311e2-904f-4acb-9937-30e50d59f3ca
    outputs:
      prod-url: ${{steps.deploy-prod.outputs.deploy-url}}

  build-dev:
    runs-on: ubuntu-latest
    name: Build DEV
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn build
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CONTENTFUL_TOKEN_PREVIEW: ${{secrets.CONTENTFUL_TOKEN_PREVIEW}}
          CONTENTFUL_TOKEN: ${{secrets.CONTENTFUL_TOKEN}}
          CONTENTFUL_ENV: staging
      - name: Upload built folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy
        uses: nwtgck/actions-netlify@v1
        id: deploy-dev
        with:
          publish-dir: './public'
          production-deploy: ${{ false }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy ${{ github.ref }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: cfb311e2-904f-4acb-9937-30e50d59f3ca
    outputs:
      dev-url: ${{steps.deploy-dev.outputs.deploy-url}}

  cypress-test:
    needs: build-dev
    if: contains(github.event_name, 'pull_request')
    runs-on: ubuntu-latest
    name: Cypress Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{needs.build-dev.outputs.dev-url}}
          record: true
          tag: ${{ github.event_name }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  lighthouse-check:
    needs: build-prod
    if: contains(github.event_name, 'pull_request')
    runs-on: ubuntu-latest
    name: Lighthouse Check
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{needs.build-prod.outputs.prod-url}}
          configPath: './lighthouserc.json'
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

  #  backstop-test:
  #    needs: build-dev
  #    runs-on: ubuntu-latest
  #    name: Backstop Test
  #    continue-on-error: true
  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: Download built folder
  #        uses: actions/download-artifact@v2
  #        with:
  #          name: public
  #          path: public
  #      - uses: ./.github/run-backstop
  #      - uses: actions/upload-artifact@v2
  #        if: failure()
  #        with:
  #          name: backstop-test
  #          path: backstop_data/

  cleanup-dev:
    runs-on: ubuntu-latest
    name: Delete artifact
    needs: [lighthouse-check]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: public
