name: Noorse site CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn build
        env:
          CONTENTFUL_TOKEN_PREVIEW: ${{secrets.CONTENTFUL_TOKEN_PREVIEW}}
      - name: Upload built folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  #  lighthouse-check:
  #    needs: build
  #    runs-on: ubuntu-latest
  #    name: Lighthouse Check
  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: Download built folder
  #        uses: actions/download-artifact@v2
  #        with:
  #          name: public
  #          path: public
  #      - name: Audit URLs using Lighthouse
  #        uses: treosh/lighthouse-ci-action@v2
  #        with:
  #          configPath: './lighthouserc.json'
  #          temporaryPublicStorage: true
  #        env:
  #          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
  #
  #  backstop-test:
  #    needs: build
  #    runs-on: ubuntu-latest
  #    name: Backstop Test
  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: Download built folder
  #        uses: actions/download-artifact@v2
  #        with:
  #          name: public
  #          path: public
  #      - uses: ./.github/run-backstop
  #      - uses: actions/upload-artifact@v2
  #        if: failure()
  #        with:
  #          name: backstop-test
  #          path: backstop_data/

  pr-preview:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Download built folder
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: cfb311e2-904f-4acb-9937-30e50d59f3ca
          build_directory: 'public'
