name: Noorse site CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - name: Upload built folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
      - name: Upload lighthouse config
        uses: actions/upload-artifact@v2
        with:
          name: lighthouserc
          path: lighthouserc.json

  lighthouse-check:
    needs: build
    runs-on: ubuntu-latest
    name: Lighthouse Check
    steps:
      - name: Download built folder
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Download lighthouse config
        uses: actions/download-artifact@v2
        with:
          name: lighthouserc
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
#      - uses: ./.github/run-backstop
#      - uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: backstop-test
#          path: backstop_data/
#
