name: Redeploy site
on:
  workflow_dispatch:
    inputs:
      preview:
        description: 'Use staged content'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PROD
    steps:
      #      - below doesn't work yet
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn build
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CONTENTFUL_TOKEN: ${{secrets.CONTENTFUL_TOKEN}}
          CONTENTFUL_TOKEN_PREVIEW: ${{secrets.CONTENTFUL_TOKEN_PREVIEW}}
          CONTENTFUL_PREVIEW: ${{ github.event.inputs.preview }}
          PROD: true
      - name: deploy
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './public'
          production-deploy: ${{ github.event.inputs.preview == 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy ${{ github.ref }}'
        env:
          TRACKING: ${{ github.event.inputs.preview == 'false' }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: cfb311e2-904f-4acb-9937-30e50d59f3ca
