name: Create Release
on:
  push:
    branches:
      - master
jobs:
  release:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    name: Create new release
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Create release commit
        run: sh ./.github/scripts/release.sh
